title: "Joderica 💚"
email: your-email@example.com
description: "A little site of love notes, for my sweet bebe."
baseurl: "/Joderica"
url: "https://bbenefield89.github.io"

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
